<?php
$clg_list=
array("Government College of Technology, Coimbatore ",
"PSG College of Technology ",
"Coimbatore Institute of Technology ",
"A.S.L. Pauls College of Engineering and Technology ",
"Christ The King Engineering College ",
"S V S College of Engineering ",
"Sree Sakthi Engineering College ",
"Coimbatore Institute of Engineering and Technology ",
"Dr. Mahalingam College of Engineering & Technology ",
"Hindusthan College of Engineering and Technology ",
"Karpagam College of Engineering (Autonomous) ",
"Kumaraguru College of Technology (Autonomous) ",
"Maharaja Engineering College ",
"Park College of Engineering and Technology ",
"Sri Krishna College of Engineering & Technology (Autonomous) ",
"Sri Ramakrishna Engineering College (Autonomous) ",
"Tamilnadu College of Engineering ",
"Sri Krishna College of Technology ",
"Maharaja Prithvi Engineering College ",
"Sri Ramakrishna Institute of Technology ",
"SNS College of Technology ",
"Sri Shakthi Institute of Engineering and Technology ",
"Nehru Institute of Engineering and Technology ",
"Maharaja Institute of Technology ",
"R V S College of Engineering and Technology ",
"INFO Institute of Engineering ",
"S N S College of Engineering ",
"Karpagam Institute of Technology ",
"Dr. N G P Institute of Technology ",
"Ranganathan Engineering College ",
"Sasurie Academy of Engineering ",
"Sri Eshwar College of Engineering ",
"Hindusthan Institute of Technology ",
"P A College of Engineering and Technology ",
"Dhanalakshmi Srinivasan College of Engineering ",
"Adithya Institute of Technology ",
"Kathir College of Engineering ",
"KTVR Knowledge Park for Engineering and Technology ",
"Easa College of Engineering and Technology ",
"Kalaignar Karunanidhi Institute of Technology ",
"KGISL Institute of Technology ",
"PPG Institute of Technology ",
"Nehru Institute of Technology ",
"Indus College of Engineering ",
"Tejaa Shakthi Institute of Technology for Women ",
"United Institute of Technology ",
"Jansons Institute of Technology ",
"Akshaya College of Engineering & Technology ",
"K P R Institute of Engineering and Technology ",
"Sriguru Institute of Technology ",
"Park College of Technology ",
"J C T College of Engineering and Technology ",
"Kalaivani College of Technology ",
"C M S College of Engineering and Technology ",
"RVS Technical Campus - Coimbatore ",
"CSI College of Engineering ",
"Al-Ameen Engineering College ",
"Bannari Amman Institute of Technology (Autonomous) ",
"Erode Sengunthar Engineering College ",
"Institute of Road and Transport Technology ",
"Kongu Engineering College (Autonomous) ",
"M.P. Nachimuthu M. Jaganathan Engineering College ",
"Nandha Engineering College ",
"Velalar College of Engineering and Technology ",
"Maharaja Engineering College for Women ",
"Shree Venkateshwara Hi-tech Engineering College ",
"Surya Engineering College ",
"Nandha College of Technology ",
"J K K Munirajah College of Technology ",
"Government College of Engineering â€“ Salem ",
"Sona College of Technology ",
"Mahendra College of Engineering ",
"The Kavery Engineering College ",
"A V S Engineering College ",
"Narasuâ€™s Sarathy Institute of Technology ",
"Bharathiyar Institute of Engineering for Women ",
"Greentech College of Engineering for Women ",
"Vivekanandha Engineering College for Women ",
"Tagore Institute of Engineering and Technology ",
"Annapoorana Engineering College ",
"Knowledge Institute of Technology ",
"V S A Educational and Charitable Trustâ€™s Group of Institutions ",
"Salem College of Engineering and Technology ",
"S R S College of Engineering and Technology ",
"The Kavery College of Engineering ",
"Annai Mathammal Sheela Engineering College ",
"K.S.Rangasamy College of Technology (Autyonomous) ",
"Mahendra Engineering College ",
"Muthayammal Engineering College ",
"Paavai Engineering College ",
"P G P College of Engineering and Technology ",
"K.S.R. College of Engineering ",
"S.S.M. College of Engineering ",
"Sengunthar Engineering College ",
"Paavaai Group of Institutions ",
"Vivekanandha College of Engineering for Women ",
"Gnanamani College of Technology ",
"Vivekanandha Institute of Engineering & Technology for Women ",
"Selvam College of Technology ",
"Paavai College of Engineering ",
"Sengunthar College of Engineering ",
"King College of Technology ",
"Mahendra Institute of Technology ",
"Vidyaa Vikas College of Engineering and Technology ",
"Excel Engineering College ",
"CMS College of Engineering ",
"Excel College of Engineering for Women ",
"Mahendra Engineering College for Women ",
"J.K.K. Nataraja College of Engineering and Technology ",
"Pavai College of Technology ",
"Gnanamani College of Engineering ",
"Vivekanandha College of Technology for women ",
"Dr. Nagarathinamâ€™s College of Engineering ",
"Excel College of Engineering and Technology ",
"Mahendra Institute of Engineering and Technology ",
"SRG Engineering College ",
"Dhanalakshmi Srinivasan Engineering College ",
"Roever Engineering College ",
"Srinivasan Engineering College ",
"Roever College of Engineering and Technology ",
"University College of Engineering, Ariyalur ",
"K.K.C College of Engineering and Technology ",
"Meenakshi Ramaswamy Engineering College ",
"University College of Engineering, Thirukkuvalai Campus ",
"Prime College of Architecture and Planning ",
"Sir Issac Newton College of Engineering and Technology ",
"A.V.C. College of Engineering ",
"E.G.S. Pillay Engineering College ",
"Sembodai Rukmani Varatharajan Engineering College ",
"Univeristy College of Engineering, Pattukkottai ",
"SMR East Coast College of Engineering and Technology ",
"K.S.K. College of Engineering and Technology ",
"Star Lion College of Engineering and Technology ",
"Arasu Engineering College ",
"P.R. Engineering College ",
"Ponnaiyah Ramajayam College of Engineering and Technology ",
"St. Josephâ€™s College of Engineering and Technology ",
"Parisutham Institute of Technology and Science ",
"Vandayar Engineering College ",
"Annai College of Engineering and Technology ",
"As-Salam College of Engineering and Technology ",
"M. Kumarasamy College of Engineering ",
"V.S.B. Engineering College ",
"Chettinad College of Engineering and Technology ",
"Karur College of Engineering ",
"V K S College of Engineering and Technology ",
"Jay Shriram Group of Institutions ",
"Erode Builder Educational Trustâ€™s Group of Institutions ",
"Professional Educational Trustâ€™s Group of Institutions ",
"Sasurie College of Engineering ",
"Angel College of Engineering and Technology ",
"Sri Ramanathan Engineering College ",
"Dr. Nallini Institute of Engineering and Technology ",
"Anjalai Ammal Mahalingam Engineering College ",
"A.R.J. College of Engineering and Technology");
$user="tnslpp";
$pass="sKxquzEt";
$host="localhost";
$db_name="tnslpp";
$table_name="basic_det";
?>